// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Big_Flat_Rock = "Big Flat Rock",
  Bush = "Bush",
  Bush_2 = "Bush_2",
  Circuit = "Circuit",
  Construction_Cone = "Construction Cone",
  Construction_Light = "Construction Light",
  Dandelion = "Dandelion",
  Dandelion_2 = "Dandelion_2",
  Green_Sycamore_Tree = "Green Sycamore Tree",
  Java_Fern = "Java Fern",
  Light_Green_Sycamore_Tree = "Light Green Sycamore Tree",
  RaceCamera = "RaceCamera",
  Rock___Empty_Land_1 = "Rock - Empty Land 1",
  Rock___Empty_Land_2 = "Rock - Empty Land 2",
  Rock___Empty_Land_2_2 = "Rock - Empty Land 2_2",
  Rock___Empty_Land_2_3 = "Rock - Empty Land 2_3",
  Rock___Empty_Land_3 = "Rock - Empty Land 3",
  Rock___Empty_Land_3_2 = "Rock - Empty Land 3_2",
  Rubber_Tire = "Rubber Tire",
  Seat1 = "Seat1",
  Seat10 = "Seat10",
  Seat11 = "Seat11",
  Seat12 = "Seat12",
  Seat13 = "Seat13",
  Seat14 = "Seat14",
  Seat15 = "Seat15",
  Seat16 = "Seat16",
  Seat17 = "Seat17",
  Seat18 = "Seat18",
  Seat19 = "Seat19",
  Seat2 = "Seat2",
  Seat20 = "Seat20",
  Seat3 = "Seat3",
  Seat4 = "Seat4",
  Seat5 = "Seat5",
  Seat6 = "Seat6",
  Seat7 = "Seat7",
  Seat8 = "Seat8",
  Seat9 = "Seat9",
  Square_Cardboard_Box = "Square Cardboard Box",
  Title = "Title",
  Tree_Stump = "Tree Stump",
  workshop_glb = "workshop.glb",
} 
