"""Extract the existing UI artwork with feathered alpha and black shadows.

The user authorized deterministic image processing. The original atlas remains
unchanged. Run with Pillow and numpy; no new image generation is involved.
"""
from collections import deque
from pathlib import Path
import json
import numpy as np
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets/UI'
SOURCE = Image.open(OUT / 'nano-racers-atlas.png').convert('RGB')
REGIONS = {
    'left': (100, 95, 375, 340),
    'right': (535, 95, 815, 340),
    'gas': (930, 55, 1265, 390),
    'brake': (1370, 55, 1705, 390),
    'drift': (43, 492, 365, 810),
    'dial': (438, 478, 883, 820),
    'panel': (893, 535, 1325, 778),
}
metadata = {}
for name, box in REGIONS.items():
    rgb = np.array(SOURCE.crop(box), dtype=np.float32)
    h, w = rgb.shape[:2]
    # Flood only the connected neutral, pale backdrop. Enclosed highlights and
    # lettering stay intact, unlike a global white/chroma key.
    pale = (rgb.min(axis=2) > 204) & (np.ptp(rgb, axis=2) < 38)
    outside = np.zeros((h, w), dtype=bool)
    queue = deque()
    for x in range(w):
        for y in (0, h-1):
            if pale[y, x]:
                outside[y, x] = True
                queue.append((x, y))
    for y in range(h):
        for x in (0, w-1):
            if pale[y, x] and not outside[y, x]:
                outside[y, x] = True
                queue.append((x, y))
    while queue:
        x, y = queue.popleft()
        for nx, ny in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
            if 0 <= nx < w and 0 <= ny < h and pale[ny,nx] and not outside[ny,nx]:
                outside[ny,nx] = True
                queue.append((nx,ny))
    mask = Image.fromarray((~outside).astype('uint8') * 255)
    # Remove isolated compression speckles, retaining the genuine curved rims.
    mask = mask.filter(ImageFilter.MedianFilter(3))
    bounds = mask.getbbox()
    assert bounds, name
    rgb = rgb[bounds[1]:bounds[3],bounds[0]:bounds[2]]
    mask = mask.crop(bounds)
    w, h = mask.size
    pad = 32
    padded = Image.new('L', (w+pad*2, h+pad*2))
    padded.paste(mask, (pad,pad))
    alpha = np.array(padded.filter(ImageFilter.GaussianBlur(.65)), dtype=np.float32) / 255
    colors = np.zeros((h+pad*2,w+pad*2,3), dtype=np.float32)
    colors[pad:pad+h,pad:pad+w] = rgb
    # Remove the pale matte from partially covered edge pixels to avoid halos.
    a = alpha[pad:pad+h,pad:pad+w,None]
    colors[pad:pad+h,pad:pad+w] = np.clip((rgb-245*(1-a))/np.maximum(a,.02),0,255)
    face = Image.fromarray(np.dstack((colors,alpha*255)).astype('uint8'), 'RGBA')
    shadow_mask = padded.filter(ImageFilter.GaussianBlur(7))
    shadow_shifted = Image.new('L', padded.size)
    shadow_shifted.paste(shadow_mask, (0,3))
    outline = padded.filter(ImageFilter.MaxFilter(5)).filter(ImageFilter.GaussianBlur(1.25))
    shadow_alpha = np.maximum(np.array(shadow_shifted)*.72, np.array(outline)*.6).astype('uint8')
    shadow = Image.new('RGBA', padded.size, (0,0,0,0))
    shadow.putalpha(Image.fromarray(shadow_alpha))
    result = Image.alpha_composite(shadow,face)
    # Prefilter fine metal texture and silhouettes before the mobile renderer's
    # bilinear sampling; oversized source textures shimmer when minified.
    target = 512 if name == 'panel' else 256
    factor = target / max(result.size)
    result = result.resize((round(result.width*factor),round(result.height*factor)), Image.Resampling.LANCZOS)
    # Transparent gutters keep bilinear sampling away from any hard texture edge.
    edge = np.array(result)[:,:,3]
    assert max(edge[0].max(),edge[-1].max(),edge[:,0].max(),edge[:,-1].max()) == 0, name
    assert np.count_nonzero((edge>0)&(edge<255)) > 1000, name
    filename = f'nano-{name}-soft.png'
    result.save(OUT / filename, optimize=True)
    metadata[name] = {'src':f'assets/UI/{filename}', 'left':-100*pad/w, 'top':-100*pad/h,
                      'width':100*(w+2*pad)/w, 'height':100*(h+2*pad)/h}
    print(f'{name}: {result.width}x{result.height}, RGBA with soft alpha and shadow')

(ROOT / 'src/ui-sprites.ts').write_text('// Generated by scripts/extract-ui-sprites.py\nexport const sprites = '+json.dumps(metadata,indent=2)+' as const\n',encoding='utf-8')
