// Generated by scripts/extract-ui-sprites.py
export const sprites = {
  "left": {
    "src": "assets/UI/nano-left-soft.png",
    "left": -13.278008298755188,
    "top": -15.238095238095237,
    "width": 126.55601659751038,
    "height": 130.47619047619048
  },
  "right": {
    "src": "assets/UI/nano-right-soft.png",
    "left": -13.389121338912133,
    "top": -15.311004784688995,
    "width": 126.77824267782427,
    "height": 130.62200956937798
  },
  "gas": {
    "src": "assets/UI/nano-gas-soft.png",
    "left": -10.847457627118644,
    "top": -10.95890410958904,
    "width": 121.69491525423729,
    "height": 121.91780821917808
  },
  "brake": {
    "src": "assets/UI/nano-brake-soft.png",
    "left": -10.884353741496598,
    "top": -10.95890410958904,
    "width": 121.7687074829932,
    "height": 121.91780821917808
  },
  "drift": {
    "src": "assets/UI/nano-drift-soft.png",
    "left": -11.636363636363637,
    "top": -11.678832116788321,
    "width": 123.27272727272727,
    "height": 123.35766423357664
  },
  "dial": {
    "src": "assets/UI/nano-dial-soft.png",
    "left": -7.619047619047619,
    "top": -10.423452768729641,
    "width": 115.23809523809524,
    "height": 120.84690553745928
  },
  "panel": {
    "src": "assets/UI/nano-panel-soft.png",
    "left": -8.060453400503778,
    "top": -15.841584158415841,
    "width": 116.12090680100755,
    "height": 131.68316831683168
  }
} as const
